// Code generated by aocgen; DO NOT EDIT.
package main

import (
	"bufio"
	"fmt"
	"os"
	"strconv"
	"strings"
	"time"
)

func main() {
	start := time.Now()
	fmt.Println("Year: 2025| Day: 02")
	input, err := parseInput("input.txt")
	if err != nil {
		panic(err)
	}

	fmt.Println("Part A: ", partA(input))
	fmt.Println("Part B: ", partB(input))
	fmt.Println("Finished: ", time.Since(start))
}

func partA(lines []string) any {
	count := 0
	ranges := strings.Split(lines[0], ",")
	for _, r := range ranges {
		ids := strings.Split(r, "-")
		start, err := strconv.Atoi(ids[0])
		if err != nil {
			fmt.Println("start invalid id", ids[0])
			continue
		}

		end, err := strconv.Atoi(ids[1])
		if err != nil {
			fmt.Println("end invalid id", ids[1])
			continue
		}

		for i := start; i <= end; i++ {
			n := strconv.Itoa(i)

			if n[:len(n)/2] == n[len(n)/2:] {
				count += i
			}
		}
	}

	return count
}

func partB(lines []string) any {
	return "not implemented"
}

func parseInput(filename string) ([]string, error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}

	lines := make([]string, 0)

	s := bufio.NewScanner(f)
	for s.Scan() {
		lines = append(lines, s.Text())
	}

	return lines, nil
}
