// Code generated by aoc; DO NOT EDIT.
package main

import (
	"strings"
	"testing"
)

var testInput = `aaa: you hhh
you: bbb ccc
bbb: ddd eee
ccc: ddd eee fff
ddd: ggg
eee: out
fff: out
ggg: out
hhh: ccc fff iii
iii: out`

var testInputB = `svr: aaa bbb
aaa: fft
fft: ccc
bbb: tty
tty: ccc
ccc: ddd eee
ddd: hub
hub: fff
eee: dac
dac: fff
fff: ggg hhh
ggg: out
hhh: out`

func TestPartA(t *testing.T) {
	input := parseTestInput()
	exampleAns := 5
	ans := partA(input)
	if ans != exampleAns {
		t.Errorf("expected: %v, actual: %v", exampleAns, ans)
	}
}

func TestPartB(t *testing.T) {
	input := parseTestInputB()
	exampleAns := 2
	ans := partB(input)
	if ans != exampleAns {
		t.Errorf("expected: %v, actual: %v", exampleAns, ans)
	}
}

func parseTestInput() []string {
	return strings.Split(testInput, "\n")
}

func parseTestInputB() []string {
	return strings.Split(testInputB, "\n")
}
