// Code generated by aoc; DO NOT EDIT.
package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
	"time"
)

func main() {
	start := time.Now()
	fmt.Println("Year: 2025| Day: 11")
	input, err := parseInput("input.txt")
	if err != nil {
		panic(err)
	}

	fmt.Println("Part A: ", partA(input))
	fmt.Println("Part B: ", partB(input))
	fmt.Println("Finished: ", time.Since(start))
}

type Graph struct {
	list map[string][]string
	memo map[string]int
}

func NewGraph() *Graph {
	return &Graph{
		list: make(map[string][]string),
		memo: make(map[string]int),
	}
}

func (g *Graph) AddEdge(from, to string)  {
	g.list[from] = append(g.list[from], to)
}

func (g *Graph) AddVertex(v string) {
	if _, exists := g.list[v]; !exists {
		g.list[v] = make([]string, 0)
	}
}

func (g *Graph) Count(v string, seenDAC, seenFFT, partB bool) int {
	if v == "dac" {
		seenDAC = true
	}
	if v == "fft" {
		seenFFT = true
	}

	k := key(v, seenDAC, seenFFT)
	if val, ok := g.memo[k]; ok {
		return val
	}

	if v == "out" {
		if partB {
			if seenDAC && seenFFT {
				g.memo[k] = 1
				return 1
			}
			g.memo[k] = 0
			return 0
		}

		g.memo[k] = 1
		return 1
	}

	total := 0
	for _, nxt := range g.list[v] {
		total += g.Count(nxt, seenDAC, seenFFT, partB)
	}

	g.memo[k] = total
	return total
}

func key(v string, seenDAC, seenFFT bool) string {
	return v + "|" + strconv.FormatBool(seenDAC) + "|" + strconv.FormatBool(seenFFT)
}

func partA(lines []string) any {
	g := NewGraph()
	for _, l := range lines {
		v := strings.Split(l, ":")
		v1 := v[0]
		g.AddVertex(v1)
		v2 := strings.Split(strings.TrimSpace(v[1]), " ")

		for _, vv := range v2 {
			g.AddVertex(vv)
			g.AddEdge(v1, vv)
		}
	}

	count := 0
	for k := range g.list {
		if k != "you" {
			continue
		}
		count = count + g.Count(k, false, false, false)
	}

	return count
}

func partB(lines []string) any {
	g := NewGraph()
	for _, l := range lines {
		v := strings.Split(l, ":")
		v1 := v[0]
		g.AddVertex(v1)
		v2 := strings.Split(strings.TrimSpace(v[1]), " ")

		for _, vv := range v2 {
			g.AddVertex(vv)
			g.AddEdge(v1, vv)
		}
	}

	count := 0
	for k := range g.list {
		if k != "svr" {
			continue
		}
		count = count + g.Count(k, false, false, true)
	}

	return count
}

func parseInput(filename string) ([]string, error) {
	_, thisFile, _, _ := runtime.Caller(0)
	dir := filepath.Dir(thisFile)
	filename = filepath.Join(dir, filename)

	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}

	lines := make([]string, 0)

	s := bufio.NewScanner(f)
	for s.Scan() {
		lines = append(lines, s.Text())
	}

	return lines, nil
}
