// Code generated by aoc; DO NOT EDIT.
package main

import (
	"strings"
	"testing"
)

var testInput = `123 328  51 64 
 45 64  387 23 
  6 98  215 314
*   +   *   + `

func TestPartA(t *testing.T) {
	input := parseTestInput()
	exampleAns := 4277556
	ans := partA(input)
	if ans != exampleAns {
		t.Errorf("expected: %v, actual: %v", exampleAns, ans)
	}
}

func TestPartB(t *testing.T) {
	input := parseTestInput()
	exampleAns := 3263827
	ans := partB(input)
	if ans != exampleAns {
		t.Errorf("expected: %v, actual: %v", exampleAns, ans)
	}
}

func parseTestInput() []string {
	//PartA: 4951502530386
	//PartB: 8486156119946
	return strings.Split(testInput, "\n")
}
