// Code generated by aocgen; DO NOT EDIT.
package main

import (
	"strings"
	"testing"
)

var testInput = `987654321111111
811111111111119
234234234234278
818181911112111`

func TestPartA(t *testing.T) {
	input := parseTestInput()
	exampleAns := 357
	ans := partA(input)
	if ans != exampleAns {
		t.Errorf("expected: %v, actual: %v", exampleAns, ans)
	}
}

func TestPartB(t *testing.T) {
	input := parseTestInput()
	exampleAns := 3121910778619
	ans := partB(input)
	if ans != exampleAns {
		t.Errorf("expected: %v, actual: %v", exampleAns, ans)
	}
}

func parseTestInput() []string {
	return strings.Split(testInput, "\n")
}
