// Code generated by aocgen; DO NOT EDIT.
package main

import (
	"bufio"
	"fmt"
	"os"
	"strconv"
	"time"
)

func main() {
	start := time.Now()
	fmt.Println("Year: 2025| Day: 03")
	input, err := parseInput("input.txt")
	if err != nil {
		panic(err)
	}

	fmt.Println("Part A: ", partA(input))
	fmt.Println("Part B: ", partB(input))
	fmt.Println("Finished: ", time.Since(start))
}

func partA(lines []string) any {
	sum := 0
	for _, l := range lines {
		max1, max2 := 0, 0
		idx := 0
		for i, c := range l[:len(l)-1] {
			joltage, err := strconv.Atoi(string(c))
			if err != nil {
				fmt.Println("could not get bank")
				continue
			}

			if joltage > max1 {
				max1 = joltage
				idx = i
			}
		}

		for _, c := range l[idx+1:] {
			joltage, err := strconv.Atoi(string(c))
			if err != nil {
				fmt.Println("could not get bank")
				continue
			}

			if joltage > max2 {
				max2 = joltage
			}
		}

		comb, err := strconv.Atoi(fmt.Sprintf("%d%d", max1, max2))
		if err != nil {
			fmt.Println("could not combine max to a number")
			return sum
		}

		sum = sum + comb

	}
	return sum
}

func partB(lines []string) any {
	sum := 0
	for _, l := range lines {
		line := ""
		idx := 0
		for i := 0; i < 12; i++ {
			max := 0
			for j := idx; j < len(l)-11+i; j++ {
				joltage, err := strconv.Atoi(string(l[j]))
				if err != nil {
					fmt.Println("could not get bank")
					continue
				}

				if joltage > max {
					max = joltage
					idx = j + 1
				}
			}

			line = fmt.Sprintf("%s%d", line, max)
		}

		s, err := strconv.Atoi(line)
		if err != nil {
			fmt.Println("could not combine max to a number")
			return sum
		}

		sum = sum + s
	}
	return sum
}

func parseInput(filename string) ([]string, error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}

	lines := make([]string, 0)

	s := bufio.NewScanner(f)
	for s.Scan() {
		lines = append(lines, s.Text())
	}

	return lines, nil
}
