// Code generated by aoc; DO NOT EDIT.
package main

import (
	"strings"
	"testing"
)

var testInput = `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`

func TestPartA(t *testing.T) {
	input := parseTestInput()
	exampleAns := 21
	ans := partA(input)
	if ans != exampleAns {
		t.Errorf("expected: %v, actual: %v", exampleAns, ans)
	}
}

func TestPartB(t *testing.T) {
	input := parseTestInput()
	exampleAns := 40
	ans := partB(input)
	if ans != exampleAns {
		t.Errorf("expected: %v, actual: %v", exampleAns, ans)
	}
}

func parseTestInput() []string {
	return strings.Split(testInput, "\n")
}
