// Code generated by aocgen; DO NOT EDIT.
package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"time"
)

func main() {
	start := time.Now()
	fmt.Println("Year: 2025| Day: 04")
	input, err := parseInput("input.txt")
	if err != nil {
		panic(err)
	}

	fmt.Println("Part A: ", partA(input))
	fmt.Println("Part B: ", partB(input))
	fmt.Println("Finished: ", time.Since(start))
}

func partA(lines []string) any {
	padded := createPadding(lines)
	rolls, _ := removePapers(padded, lines)

	return rolls
}

func partB(lines []string) any {
	padded := createPadding(lines)
	sum := 0
	for {
		rolls, c := removePapers(padded, lines)
		padded = replaceWithDot(padded, c)
		sum += rolls
		if rolls == 0 {
			return sum
		}
	}
}

func createPadding(lines []string) []string {
	h := len(lines)
	w := len(lines[0])

	topBottom := ""
	for i := 0; i < w+2; i++ {
		topBottom += string("#")
	}

	padded := make([]string, 0, h+2)

	for i := 0; i < 1; i++ {
		padded = append(padded, topBottom)
	}

	for _, row := range lines {
		newRow := ""
		for i := 0; i < 1; i++ {
			newRow += string("#")
		}
		newRow += row
		for i := 0; i < 1; i++ {
			newRow += string("#")
		}
		padded = append(padded, newRow)
	}

	for i := 0; i < 1; i++ {
		padded = append(padded, topBottom)
	}

	return padded
}

type Cordinates struct {
	I int
	J int
}

func removePapers(padded, lines []string) (int, []Cordinates) {
	h := len(lines)
	w := len(lines[0])

	c := make([]Cordinates, 0)

	rolls := 0
	for i := 1; i < h+1; i++ {
		for j := 1; j < w+1; j++ {
			if strings.Split(padded[i], "")[j] != "@" {
				continue
			}

			// fmt.Printf("checking this: %v, i,j: %v, %v\n", strings.Split(padded[i], "")[j], i, j)

			adj := 0

			top := strings.Split(padded[i-1], "")
			if top[j-1] == "@" {
				adj++
			}

			if top[j] == "@" {
				adj++
			}

			if top[j+1] == "@" {
				adj++
			}

			row := strings.Split(padded[i], "")
			if row[j-1] == "@" {
				adj++
			}

			if row[j+1] == "@" {
				adj++
			}

			bottom := strings.Split(padded[i+1], "")
			if bottom[j-1] == "@" {
				adj++
			}

			if bottom[j] == "@" {
				adj++
			}

			if bottom[j+1] == "@" {
				adj++
			}

			// fmt.Printf("Checking window\n")
			// fmt.Printf("top: %v|%v|%v\nrow: %v| |%v\nbot: %v|%v|%v\n",
			// 	top[j-1],
			// 	top[j],
			// 	top[j+1],
			// 	row[j-1],
			// 	row[j+1],
			// 	bottom[j-1],
			// 	bottom[j],
			// 	bottom[j+1])

			if adj < 4 {
				rolls++
				c = append(c, Cordinates{I: i, J: j})
				// fmt.Printf("roll can access cordinates, i=%v|j=%v\n", i, j)
			}

		}
	}

	return rolls, c
}

func replaceWithDot(old []string, coords []Cordinates) []string {
	oldGrid := make([][]rune, len(old))
	for i := range old {
		oldGrid[i] = []rune(old[i])
	}

	for _, c := range coords {
		r := c.I
		col := c.J

		oldGrid[r][col] = '.'
	}

	newPadded := make([]string, len(oldGrid))
	for i := range oldGrid {
		newPadded[i] = string(oldGrid[i])
	}

	return newPadded
}

func parseInput(filename string) ([]string, error) {
	_, thisFile, _, _ := runtime.Caller(0)
	dir := filepath.Dir(thisFile)
	filename = filepath.Join(dir, filename)

	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}

	lines := make([]string, 0)

	s := bufio.NewScanner(f)
	for s.Scan() {
		lines = append(lines, s.Text())
	}

	return lines, nil
}
