// Code generated by aocgen; DO NOT EDIT.
package main

import (
	"strings"
	"testing"
)

var testInput = `..@@.@@@@.
@@@.@.@.@@
@@@@@.@.@@
@.@@@@..@.
@@.@@@@.@@
.@@@@@@@.@
.@.@.@.@@@
@.@@@.@@@@
.@@@@@@@@.
@.@.@@@.@.`

func TestPartA(t *testing.T) {
	input := parseTestInput()
	exampleAns := 13
	ans := partA(input)
	if ans != exampleAns {
		t.Errorf("expected: %v, actual: %v", exampleAns, ans)
	}
}

func TestPartB(t *testing.T) {
	input := parseTestInput()
	exampleAns := 43
	ans := partB(input)
	if ans != exampleAns {
		t.Errorf("expected: %v, actual: %v", exampleAns, ans)
	}
}

func parseTestInput() []string {
	return strings.Split(testInput, "\n")
}
