// Code generated by aocgen; DO NOT EDIT.
package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
	"time"
)

func main() {
	start := time.Now()
	fmt.Println("Year: 2025| Day: 01")
	input, err := parseInput("input.txt")
	if err != nil {
		panic(err)
	}

	// fmt.Println("Part A: ", partA(input))
	fmt.Println("Part B: ", partB(input))
	fmt.Println("Finished: ", time.Since(start))
}

func partA(lines []string) any {
	start := 50
	count := 0
	for _, l := range lines {
		rotations := strings.Split(l, "")
		rotation := rotations[0]
		times := strings.Join(rotations[1:], "")

		t, err := strconv.Atoi(times)
		if err != nil {
			fmt.Println("could not parse times")
			continue
		}

		switch rotation {
		case "R":
			start = (start + t + 100) % 100
		case "L":
			start = (start - t + 100) % 100
		default:
			fmt.Println("something went wrong continue")
			continue
		}

		if start == 0 {
			count++
		}
	}
	return count
}

func partB(lines []string) any {
	start := 50
	count := 0
	for _, l := range lines {
		rotations := strings.Split(l, "")
		rotation := rotations[0]
		times := strings.Join(rotations[1:], "")

		t, err := strconv.Atoi(times)
		if err != nil {
			fmt.Println("could not parse times")
			continue
		}

		for _ = range t {
			switch rotation {
			case "R":
				start = (start + 1 + 100) % 100
			case "L":
				start = (start - 1 + 100) % 100
			default:
				fmt.Println("something went wrong continue")
				continue
			}

			if start == 0 {
				count++
			}
		}
	}
	return count
}

func parseInput(filename string) ([]string, error) {
	_, thisFile, _, _ := runtime.Caller(0)
	dir := filepath.Dir(thisFile)
	filename = filepath.Join(dir, filename)

	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}

	lines := make([]string, 0)

	s := bufio.NewScanner(f)
	for s.Scan() {
		lines = append(lines, s.Text())
	}

	return lines, nil
}
