// Code generated by aocgen; DO NOT EDIT.
package main

import (
	"strings"
	"testing"
)

var testInput = `L68
L30
R48
L5
R60
L55
L1
L99
R14
L82`

func TestPartA(t *testing.T) {
	input := parseTestInput()
	exampleAns := 3
	ans := partA(input)
	if ans != exampleAns {
		t.Errorf("expected: %v, actual: %v", exampleAns, ans)
	}
}

func TestPartB(t *testing.T) {
	input := parseTestInput()
	exampleAns := 6
	ans := partB(input)
	if ans != exampleAns {
		t.Errorf("expected: %v, actual: %v", exampleAns, ans)
	}
}

func parseTestInput() []string {
	return strings.Split(testInput, "\n")
}
