// Code generated by aoc; DO NOT EDIT.
package main

import (
	"strings"
	"testing"
)

var testInput = `7,1
11,1
11,7
9,7
9,5
2,5
2,3
7,3`

func TestPartA(t *testing.T) {
	input := parseTestInput()
	exampleAns := 50
	ans := partA(input)
	if ans != exampleAns {
		t.Errorf("expected: %v, actual: %v", exampleAns, ans)
	}
}

func TestPartB(t *testing.T) {
	input := parseTestInput()
	exampleAns := 24
	ans := partB(input)
	if ans != exampleAns {
		t.Errorf("expected: %v, actual: %v", exampleAns, ans)
	}
}

func parseTestInput() []string {
	return strings.Split(testInput, "\n")
}

//grid := [8][14]string{}
//	for i :=0; i < 8; i++{
//		for j := 0; j < 14; j++{
//			grid[i][j] = "."
//		}
//	}
//
//	for _, t := range tiles {
//		grid[t.Y][t.X] = "#"
//	}
//
//	for _, row := range grid{
//		fmt.Println(row)
//	}
//
//	//..............
//	//.......#XXX#..
//	//.......X...X..
//	//..#XXXX#...X..
//	//..X........X..
//	//..#XXXXXX#.X..
//	//.........X.X..
//	//.........#X#..
//	//..............